include: package:lint/analysis_options.yaml

linter:
  rules:
#    non_constant_identifier_names: false
    avoid_print: true
    avoid_setters_without_getters: false
    sort_pub_dependencies: false

analyzer:
  errors:
    unused_import: warning

strong-mode:
    implicit-casts: false
