include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_print: false
    avoid_setters_without_getters: false
    sort_pub_dependencies: false
    avoid_positional_boolean_parameters: false

analyzer:
  errors:
    unused_import: warning

strong-mode:
    implicit-casts: false
