name: chaotic
description: A new Flutter framework ,helpers and widgets.
version: 1.1.0
homepage: https://github.com/Flutterry/chaotic.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.13
  get: ^4.1.4
  bot_toast: ^4.0.1
  easy_localization: ^3.0.0
  flutter_spinkit: ^5.0.0
  provider: ^5.0.0
  dio: ^4.0.0
  process_run: ^0.12.1
  country_code_picker: ^2.0.2
  lint: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
